<a href="https://colab.research.google.com/github/RaunakBatra/task_3/blob/main/ModelNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
df=pd.read_csv('recipe_final (1).csv')

In [15]:
df

,Unnamed: 0,recipe_id,recipe_name,aver_rate,image_url,review_nums,calories,fat,carbohydrates,protein,cholesterol,sodium,fiber,ingredients_list
0,0,222388,Homemade Bacon,5.00,https://images.media-allrecipes.com/userphotos...,3,15,36,1,42,21,81,2,"['pork belly', 'smoked paprika', 'kosher salt'..."
1,1,240488,"Pork Loin, Apples, and Sauerkraut",4.76,https://images.media-allrecipes.com/userphotos...,29,19,18,10,73,33,104,41,"['sauerkraut drained', 'Granny Smith apples sl..."
2,2,218939,Foolproof Rosemary Chicken Wings,4.57,https://images.media-allrecipes.com/userphotos...,12,17,36,2,48,24,31,4,"['chicken wings', 'sprigs rosemary', 'head gar..."
3,3,87211,Chicken Pesto Paninis,4.62,https://images.media-allrecipes.com/userphotos...,163,32,45,20,65,20,43,18,"['focaccia bread quartered', 'prepared basil p..."
4,4,245714,Potato Bacon Pizza,4.50,https://images.media-allrecipes.com/userphotos...,2,8,12,5,14,7,8,3,"['red potatoes', 'strips bacon', 'Sauce:', 'he..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48730,48730,222886,Grateful Dead Cocktail,3.50,https://images.media-allrecipes.com/userphotos...,4,20,1,6,1,0,1,0,"['fluid ounce tequila', 'fluid ounce vodka', '..."
48731,48731,25650,Cheese Filling For Pastries,4.33,https://images.media-allrecipes.com/userphotos...,3,6,14,2,4,13,3,1,"['raisins', 'brandy', 'cream cheese', 'white s..."
48732,48732,23544,Peach Smoothie,3.62,https://images.media-allrecipes.com/userphotos...,21,8,7,8,10,3,3,8,"['sliced peaches drained', 'scoops vanilla ice..."
48733,48733,170710,Double Dare Peaches,4.71,https://images.media-allrecipes.com/userphotos...,19,20,33,16,11,25,7,5,"['butter', 'habanero peppers', 'fresh peaches'..."
48734,48734,79774,All-Purpose Marinara Sauce,4.50,https://images.media-allrecipes.com/userphotos...,2,2,3,2,3,0,16,6,"['olive oil', 'bulb garlic', 'tomatoes chopped..."

In [16]:
df.head()

,Unnamed: 0,recipe_id,recipe_name,aver_rate,image_url,review_nums,calories,fat,carbohydrates,protein,cholesterol,sodium,fiber,ingredients_list
0,0,222388,Homemade Bacon,5.00,https://images.media-allrecipes.com/userphotos...,3,15,36,1,42,21,81,2,"['pork belly', 'smoked paprika', 'kosher salt'..."
1,1,240488,"Pork Loin, Apples, and Sauerkraut",4.76,https://images.media-allrecipes.com/userphotos...,29,19,18,10,73,33,104,41,"['sauerkraut drained', 'Granny Smith apples sl..."
2,2,218939,Foolproof Rosemary Chicken Wings,4.57,https://images.media-allrecipes.com/userphotos...,12,17,36,2,48,24,31,4,"['chicken wings', 'sprigs rosemary', 'head gar..."
3,3,87211,Chicken Pesto Paninis,4.62,https://images.media-allrecipes.com/userphotos...,163,32,45,20,65,20,43,18,"['focaccia bread quartered', 'prepared basil p..."
4,4,245714,Potato Bacon Pizza,4.50,https://images.media-allrecipes.com/userphotos...,2,8,12,5,14,7,8,3,"['red potatoes', 'strips bacon', 'Sauce:', 'he..."

In [17]:
df.tail()

,Unnamed: 0,recipe_id,recipe_name,aver_rate,image_url,review_nums,calories,fat,carbohydrates,protein,cholesterol,sodium,fiber,ingredients_list
48730,48730,222886,Grateful Dead Cocktail,3.50,https://images.media-allrecipes.com/userphotos...,4,20,1,6,1,0,1,0,"['fluid ounce tequila', 'fluid ounce vodka', '..."
48731,48731,25650,Cheese Filling For Pastries,4.33,https://images.media-allrecipes.com/userphotos...,3,6,14,2,4,13,3,1,"['raisins', 'brandy', 'cream cheese', 'white s..."
48732,48732,23544,Peach Smoothie,3.62,https://images.media-allrecipes.com/userphotos...,21,8,7,8,10,3,3,8,"['sliced peaches drained', 'scoops vanilla ice..."
48733,48733,170710,Double Dare Peaches,4.71,https://images.media-allrecipes.com/userphotos...,19,20,33,16,11,25,7,5,"['butter', 'habanero peppers', 'fresh peaches'..."
48734,48734,79774,All-Purpose Marinara Sauce,4.50,https://images.media-allrecipes.com/userphotos...,2,2,3,2,3,0,16,6,"['olive oil', 'bulb garlic', 'tomatoes chopped..."

In [18]:
vectorizer=TfidfVectorizer()
X_ingredients= vectorizer.fit_transform(df['ingredients_list'])

In [19]:
scaler= StandardScaler()
x_numerical= scaler.fit_transform(df[['fat','calories','protein','cholesterol','sodium','fiber','carbohydrates']])

In [20]:
combined= np.hstack([X_ingredients.toarray(),x_numerical])

In [21]:
knn= NearestNeighbors(metric='euclidean',n_neighbors=3)
knn.fit(combined)

NearestNeighbors(metric='euclidean', n_neighbors=3)

In [22]:
def recommendation_recipes(input_features):
  input_features_scaled= scaler.transform([input_features[:7]])
  input_ingredients_transformed=vectorizer.transform([input_features[7]])
  input_combined=np.hstack([input_features_scaled,input_ingredients_transformed.toarray()])
  distances, indices=knn.kneighbors(input_combined)
  recommended_recipes=df.iloc[indices[0]]
  return recommended_recipes[['recipe_name','ingredients_list','image_url']]

In [23]:
input_features=[ 15, 36, 1, 42, 21, 81, 2, 'pork belly, smoked paprika, kosher salt']

In [24]:
recommendation_recipes(input_features)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

,recipe_name,ingredients_list,image_url
27021,Scripture Cake,"['butter', 'white sugar Jeremiah 6:20', 'eggs ...",http://images.media-allrecipes.com/userphotos/...
40002,Caesar Salad Pinwheels,"['cream cheese', 'sun-dried tomatoes in oil', ...",https://images.media-allrecipes.com/userphotos...
25445,Lemon Cake Pie,"['10-inch pie crust unbaked', 'white sugar', '...",http://images.media-allrecipes.com/userphotos/...